stages:
  - run

mirror:
  stage: run
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

sensor:
  stage: run
  script:
    - setsid ./ci/sensor.sh
    - setsid ./ci/screen.sh
  only:
    - /^(main.*)$/
  tags:
    - cwcloud-demo-sensor
