stages:
  - publish
  - start

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

sensor:
  stage: start
  script:
    - setsid ./ci/sensor.sh
  only:
    - /^(main.*)$/
  tags:
    - cwcloud-demo-sensor

#screen:
#  stage: start
#  script:
#    - setsid ./ci/screen.sh
#  only:
#    - /^(main.*)$/
#  tags:
#    - cwcloud-demo-sensor
