stages:
  - publish
  - start

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

sensor:
  stage: publish
  script:
    - setsid ./ci/sensor.sh
  only:
    - /^(main.*)$/
  tags:
    - cwcloud-demo-sensor
